name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies for requirements and testing
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
          pip install pylint flake8 mypy pytest pytest-cov
          pip list

      - name: Lint with pylint
        run: |
          echo "Eseguo pylint solo sui file Python del progetto (ignoro venv/):"
          find . -type f -name "*.py" ! -path "./venv/*" > pyfiles.txt
          cat pyfiles.txt
          pylint $(cat pyfiles.txt) --ignore=venv || true

      - name: Lint with flake8
        run: |
          echo "Eseguo flake8 (ignoro venv/)..."
          flake8 . --exclude=venv --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --exclude=venv --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Lint with mypy
        run: |
          echo "Eseguo mypy (ignoro venv/)..."
          find . -type f -name "*.py" ! -path "./venv/*" > pyfiles.txt
          mypy $(cat pyfiles.txt) || true

      #- name: Test with pytest
      # run: pytest --cov=src_exercises --cov-report=term-missing

